type ShipmentItemQuantityType {
  amount: Int
  code: String
  description: String
}

type ShipmentItemReferenceType {
  order: String
  delivery: String
  containerNo: String
  truckId: String
  trailerId: String
  document: String
  seal: String
}

type ShipmentItemMaterialType {
  id: String
  description: String
}

type ShipmentItemTemperatureRangeType {
  from: Float
  to: Float
  unit: String
}

type ShipmentItemTemperatureType {
  condition: String
  range: ShipmentItemTemperatureRangeType
}

type ShipmentItemDimensionType {
  length: Float
  width: Float
  height: Float
  uom: String
}

type ShipmentItemTaxableType {
  type: String
  quantity: Float
}

type ShipmentItemCalcSettingType {
  costRelevant: Boolean
  itemize: Boolean
  keys: JSON
  linkField: String
}

type ShipmentItemType {
  id: String
  shipmentId: String
  parentItemId: String
  level: Int
  quantity: ShipmentItemQuantityType
  type: String
  itemType: String
  number: String
  description: String
  commodity: String
  references: ShipmentItemReferenceType
  material: ShipmentItemMaterialType
  DG: Boolean
  DGClassType: String
  temperature: ShipmentItemTemperatureType
  weight_net: Float
  weight_tare: Float
  weight_gross: Float
  weight_unit: String
  dimensions: ShipmentItemDimensionType
  taxable: [ShipmentItemTaxableType]
  calcSettings: ShipmentItemCalcSettingType
}

input SaveShipmentItemInput {
  id: String
  shipmentId: String!
  parentItemId: String
  level: Int
  quantity: JSON
  type: String
  itemType: String
  number: String
  description: String
  commodity: String
  references: JSON
  material: JSON
  DG: Boolean
  DGClassType: String
  temperature: JSON
  weight_net: Float
  weight_tare: Float
  weight_gross: Float
  weight_unit: String
  dimensions: JSON
  taxable: [JSON]
  calcSettings: JSON
}

input ItemInput {
  condition: String
}

input ChangeShipmentItemParentNodeInput {
  shipmentId: String
  id: String
  targetParentItemId: String
}

input DeleteShipmentItemInput {
  id: String
}

input GetShipmentItemsInput {
  shipmentId: String!
  level: Int
}

extend type Query {
  getShipmentItems(input: GetShipmentItemsInput!): [ShipmentItemType]
}

extend type Mutation {
  saveShipmentItem(input: SaveShipmentItemInput): String
  changeShipmentItemParentNode(
    input: ChangeShipmentItemParentNodeInput
  ): Boolean
  deleteShipmentItem(input: DeleteShipmentItemInput): Boolean
}
