type User {
    id: ID!
    name: String!
}

input AddressInputMetadata {
    id: String
    type: String
    street2: String
    street3: String
    fax: String
    taxId: String
    isResidential: Boolean
    metadata: String
    isComplete: Boolean
}

input AddressInput {
    contactName: String!
    street1: String!
    city: String!
    state: String!
    phone: String!
    email: String!
    companyName: String
    countryCode: String!
    postalCode: String!
}

type AddressType {
    id: String
    isComplete: Boolean
    contactName: String
    street1: String
    city: String
    state: String
    phone: String
    email: String
    type: String
    postalCode: String
    street2: String
    street3: String
    companyName: String
    fax: String
    taxId: String
    isResidential: Boolean
    metadata: String
    countryCode: String
}

type AddressOutput {
    isComplete: Boolean
    contactName: String
    street1: String
    city: String
    state: String
    countryCode: String
    phone: String
    email: String
    type: String
    postalCode: String
    street2: String
    street3: String
    companyName: String
    fax: String
    isResidential: String
    metadata: String
    id: String
    createdAt: String
    updatedAt: String
}

input WeightInput {
    value: Float
	unit: String
}

type WeightType {
    value: Float
	unit: String
}

input DimensionInput {
    width: Float
    height: Float
    length: Float
    depth: Float
    unit: String
}

type DimensionType {
    width: Float
    height: Float
    depth: Float
    unit: String
}

input Price {
    amount: Float
    currency: String
}

type PriceType {
    amount: Float
    currency: String
}

input ItemInput {
    description: String!
    originCountry: String!
    quantity: Float!
    sku: String
    weight: WeightInput!
    price: Price!
}

type ItemType {
    description: String
    originCountry: String
    quantity: Float
    sku: String
    weight: WeightType
    price: PriceType
}

input ParcelInput {
    length: Float!
    distanceUnit: String!
    description: String!
    boxType: String!
    weight: WeightInput!
    width:  Float!
    height:  Float!
    massUnit: String!
    dimension: DimensionInput!
    items: [ItemInput!]!
}

type ParcelType {
    length: String
    distanceUnit: String
    description: String
    boxType: String
    weight: WeightType
    height: String
    massUnit: String
    depth: String
    dimension: DimensionType
    items: [ItemType]
}

input ShipperAccount {
    id: String
    username: String
    password: String
    accountNumber: String
}

type ShipperAccountType {
    id: String
    slug: String
    description: String
}

type ChargeType {
    amount: Float
	currency: String
}

type LocalChargeType {
    amountLocal: String
    currencyLocal: String
}

type DetailedChargesType {
    type: String
    charge: ChargeType
}

type RateOutputMetadata {
    chargeWeight: WeightType
    localTotalCharge: LocalChargeType
    shipperAccount: ShipperAccountType
    serviceType: String
    serviceName: String
    serviceToken: String
    pickupDeadline: String
    objectOwner: String
    bookingCutOff: String
    durationTerms: String
    createdAt: String
    updatedAt: String
    detailedCharges: [DetailedChargesType]
    cutOffTime: String
}

type RateOutput {
    id: String
    status: String
    totalCharge: ChargeType
    deliveryDate: String
    metadata: RateOutputMetadata
    serviceType: String
}

input CommoditiesInput {
    numberOfPieces: Int
    description: String
    countryOfManufacture: String
    quantity: Float
    unitPrice: Float
    customsValue: Float
}

input InternationalDetailInput {
    commodities: CommoditiesInput
}

input ShipmentMetadataType {
    pickupLocationCloseTime: String
    pickupLocation: String
    declaredValue: Float
    declaredValueCurrecyCode: String
    paymentInfo: String
    content: String
    labelType: String
    internationalDetail: InternationalDetailInput
    customersReference: String
}

input ShipmentInputObject {
    parcels: [ParcelInput!]!
    shipFrom: AddressInput!
    shipTo: AddressInput!
}

input ShipmentInput {
    shipment: ShipmentInputObject!
    shipmentDate: String!
    getLabel: Boolean
    serviceType: String!
    shipmentMetadata: ShipmentMetadataType
}

type FileLabel {
    paper_size: String
    url: String
    file_type: String
}

type FileInvoice {
    paper_size: String
    url: String
    file_type: String
}

type FileType {
    label: FileLabel
    invoice: FileInvoice
    customs_declaration: String
	manifest: String
}

type Label {
    id: String
    status: String
    tracking_numbers: [String]
    files: FileType
    rate: RateOutput
}

type MessageType {
    source: String
    code: String
    text: String
}

type ValidationResultsType {
    isValid: Boolean
    messages: [MessageType]
}

type AddressValidation {
    id: String
    isComplete: Boolean
    contactName: String
    street1: String
    city: String
    state: String
    country: String
    phone: String
    email: String
    type: String
    postalCode: String
    street2: String
    street3: String
    companyName: String
    fax: String
    taxId: String
    zip: String
    isResidential: Boolean
    metadata: String
    status: String
    createdAt: String
    updatedAt: String
    objectOwner: String
    recommendedAddress: AddressType
    validationResults: ValidationResultsType
}

type ManifestLabel {
    id: String
    manifested: Boolean
}

type Manifest {
    manifest: ManifestType
}

type ManifestType {
    id: String
    status: String
    createdAt: String
    updatedAt: String
}

type LabelTypeCanceled {
    id: String
}

type CanceledLabel {
    id: String
    status: String
    label: LabelTypeCanceled
    createdAt: String
    updatedAt: String
}

input TrackingInput {
    trackingNumber: String
    trackingSlug: String
}

input CustomFieldsInput {
    productName: String
    productPrice: String
}

input CreateTrackingInput {
    trackingNumber: String
    slug: String
    title: String
    orderId: String
    orderIdPath: String
    language: String
    pickupLocation: String
    pickupNote: String
    customFields: CustomFieldsInput
    deliveryType: String
    orderPromisedDeliveryDate: String
    trackingOriginCountry: String
    trackingDestinationCountry: String
    trackingKey: String
    trackingPostalCode: String
    trackingShipDate: String
    trackingState: String
    note: String
    destinationCountryIso3: String
    customerName: String
    smses: [String]
    emails: [String]
    ios: [String]
    android: [String]
}

type TrackingStatusType {
    id: String
    status: String
    location: AddressType
    statusDate: String
    statusDetails: String
    createdAt: String
    updatedAt: String
}

type DestinationServiceAreaType {
    serviceAreaCode: String
    description: String
    facilityCode: String
}

type TrackingOutput {
    id: String
    slug: String
    serviceType: String
    serviceToken: String
    serviceName: String
    createdAt: String
    updatedAt: String
    lastIpdatedAt: String
    trackingNumber: String
    active: Boolean
    android: [String]
    customFields: String
    customerName: String
    deliveryTime: Int
    destinationCountryIso3: String
    courierDestinationCountryIso3: String
    emails: [String]
    expectedDelivery: String
    ios: [String]
    note: String
    orderId: String
    orderIdPath: String
    originCountryIso3: String
    shipmentPackageCount: Int
    shipmentPickupDate: String
    shipmentDeliveryDate: String
    messageTime: String
    messageReference: String
    consigneeName: String
    destinationServiceArea: DestinationServiceAreaType
    shipmentType: String
    shipmentWeight: Int
    shipmentWeightUnit: String
    signedBy: String
    smses: [String]
    source: String
    tag: String
    subtag: String
    subtagMessage: String
    title: String
    trackedCount: Int
    lastMileTrackingSupported: String
    language: String
    uniqueToken: String
    checkpoints: [String]
    subscribedSmses: [String]
    subscribedEmails: [String]
    returnToSender: Boolean
    trackingAccountNumber: String
    trackingOriginCountry: String
    trackingDestinationCountry: String
    trackingKey: String
    trackingPostalCode: String
    trackingShipDate: String
    trackingState: String
    orderPromisedDeliveryDate: String
    deliveryType: String
    pickupLocation: String
    pickupNote: String
    courierTrackingLink: String
    courierRedirectLink: String
    firstAttemptedAt: String
    shipFrom: AddressType
    shipTo: AddressType
    trackingStatus: TrackingStatusType
    trackingHistory: [TrackingStatusType]
    transaction: String
    parcels: [ParcelType]
}


input BillingInput {
    paidBy: String
}

input CustomInput {
    billing: BillingInput
    termsOfTrade: String
    purpose: String
}

input ManifestCreationInput {
    shipperManifestAccountId: String
    labelIds: [String]
    shipmentDate: String
    shipFromId: String
}

input InvoiceInput {
    date: String
    number: String
}

input LabelInput {
    serviceType: String
    shipment: ShipmentInput
}

type LabelOutput {
    id: String
    labelUrl: String
    trackingNumbers: [String]
    createdAt: String
    status: String
}

type ShipmentOutputMetadataType {
    objectOwner: String
    addressReturn: AddressType
    shipperAccounts: [String]
    messages: [String]
    status: String
    dispatchConfirmationNumber: String
    labelImageFormat: String
    graphicImage: String
    parcels: ParcelType
}

type ShipmentOutput {
    id: String
    shipmentDate: String
    trackingNumber: String
    addressReturnId: String
    rates: [RateOutput]
    createdAt: String
    metadata: ShipmentOutputMetadataType
    label: LabelOutput
}

enum ServiceTypes {
  shippo
  postmen
  dhlexpress
}

type Query {
    rates(type: String!, shipment: ShipmentInput!): [RateOutput]
    labels(type: String!): [LabelOutput!]!,
    manifest(type: String!, manifestId: String!): ManifestType!
    trackings(type: String!): [TrackingOutput!]!
    trackingStatus(type: String!, tracking: TrackingInput): TrackingOutput
    manifests(type: String!): [ManifestType!]!  
    shipments(type: ServiceTypes!): [ShipmentOutput]! 
}

type Mutation {
    validateAddress(type: String!, address: AddressInput!): AddressValidation!,
    createManifest(type: String!, manifest: ManifestCreationInput!): ManifestType
    cancelOrDeleteLabel(type: String!, labelId: String!): CanceledLabel!
    createTracking(type: String!, tracking: CreateTrackingInput!): TrackingOutput!
    createLabel(type: String!, shipment: ShipmentInput!): LabelOutput!
    createShipment(type: String!, shipment: ShipmentInput!): ShipmentOutput!
    createAddress(type: String!, address: AddressInput!): AddressOutput!
}